Fix test failures with latest spock.
Error was as follows:

java.lang.IllegalAccessError: Update to non-static final field com.seriouslypro.pnpconvert.ConverterSpec.noPlacements attempted from a different method ($spock_initializeFields) than the initializer method <init>

	at com.seriouslypro.pnpconvert.ConverterSpec.$spock_initializeFields(ConverterSpec.groovy)